name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Build and Push Container
        run: gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_PROJECT }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.GCP_PROJECT }} \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_PROJECT }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --set-env-vars="SECRET_KEY=${{ secrets.SECRET_KEY }},MONGO_URI=${{ secrets.MONGO_URI }}"